"use client";

import { useEffect, useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from "recharts";

// The deployed API Gateway base URL. (Later: move to an env var / config.)
const API_BASE = "https://m25yqjhn7e.execute-api.us-east-1.amazonaws.com/Prod";
const USER_ID = "u123"; // MVP: hardcoded; Phase 6 derives this from Clerk auth.

const PRIORITY = { red: "🔴", yellow: "🟡", green: "🟢" };

function barColor(score) {
  if (score >= 67) return "#2e7d32";
  if (score >= 40) return "#f9a825";
  return "#c0392b";
}

export default function Dashboard() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(`${API_BASE}/reports?user_id=${USER_ID}`)
      .then((r) => r.json())
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  if (error) return <Shell><p style={{ color: "#c0392b" }}>Error: {error}</p></Shell>;
  if (!data) return <Shell><p>Loading…</p></Shell>;

  const r = data.latest;
  if (!r) return <Shell><p>No reports yet. Run an analysis first.</p></Shell>;

  const reviewCount = data.history?.[0]?.review_count ?? "—";
  const reportDate = data.history?.[0]?.report_date ?? "";

  return (
    <Shell>
      <div style={{ display: "flex", gap: 16, marginBottom: 24 }}>
        <Kpi label="Sentiment" value={`${r.sentiment_score}/100`} big />
        <Kpi label="Reviews analysed" value={reviewCount} />
        <Kpi label="Confidence" value={r.confidence_score} />
      </div>

      <p style={{ fontSize: 16, lineHeight: 1.6, background: "#f4f1ea", padding: 16, borderRadius: 8 }}>
        {r.week_summary}
      </p>

      <h2>Product sentiment</h2>
      <div style={{ background: "#fff", borderRadius: 8, padding: 16, border: "1px solid #eee" }}>
        <ResponsiveContainer width="100%" height={260}>
          <BarChart data={r.products || []}>
            <XAxis dataKey="product_name" fontSize={12} />
            <YAxis domain={[0, 100]} fontSize={12} />
            <Tooltip />
            <Bar dataKey="sentiment_score" radius={[4, 4, 0, 0]}>
              {(r.products || []).map((p, i) => (
                <Cell key={i} fill={barColor(p.sentiment_score)} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      <h2>Priority themes</h2>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
        <thead>
          <tr style={{ textAlign: "left", background: "#fafafa" }}>
            <th style={th}>Theme</th>
            <th style={th}>Mentions</th>
            <th style={th}>Severity</th>
            <th style={th}>Recommended actions</th>
          </tr>
        </thead>
        <tbody>
          {(r.themes || []).map((t, i) => (
            <tr key={i}>
              <td style={td}>{PRIORITY[t.priority] || ""} <b>{t.theme}</b></td>
              <td style={td}>{t.mentions}</td>
              <td style={td}>{t.severity}</td>
              <td style={td}>
                <ul style={{ margin: 0, paddingLeft: 18 }}>
                  {(t.recommended_actions || []).map((a, j) => (
                    <li key={j}>{a}</li>
                  ))}
                </ul>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {r.anomalies?.length > 0 && (
        <>
          <h2>Anomalies</h2>
          <ul>{r.anomalies.map((a, i) => <li key={i} style={{ marginBottom: 6 }}>{a}</li>)}</ul>
        </>
      )}

      <p style={{ color: "#999", fontSize: 12, marginTop: 32 }}>
        Report {reportDate} · Generated by reviewiq
      </p>
    </Shell>
  );
}

function Shell({ children }) {
  return (
    <main style={{ fontFamily: "system-ui, sans-serif", maxWidth: 900, margin: "0 auto", padding: 24 }}>
      <h1 style={{ color: "#c0392b", marginBottom: 0 }}>reviewiq</h1>
      <p style={{ color: "#777", marginTop: 4 }}>AI Review Intelligence</p>
      {children}
    </main>
  );
}

function Kpi({ label, value, big }) {
  return (
    <div style={{ flex: 1, background: "#fff", border: "1px solid #eee", borderRadius: 8, padding: 16 }}>
      <div style={{ color: "#777", fontSize: 13 }}>{label}</div>
      <div style={{ fontWeight: "bold", fontSize: big ? 32 : 24, marginTop: 4 }}>{value}</div>
    </div>
  );
}

const th = { padding: 8, borderBottom: "2px solid #eee" };
const td = { padding: 8, borderBottom: "1px solid #eee", verticalAlign: "top" };
